<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day16_numpy_projcet/miniprojcet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 16 Numpy mini projcet

Student Marks Analysis System

🎯 Project Goal
Analyze marks of 10 students in 5 subjects using NumPy.
Topics covered:
Arrays
Indexing & Slicing
Broadcasting
Statistics
Reshaping
Boolean Indexing
Random Module

In [10]:
# import numpy
import numpy as np
# Genreate student mark
# use random_seed to stay same numbers after refreshing
np.random.seed(42)
marks = np.random.randint(35,101,size = (10,5))
print(marks)
#Array information
print("shape",marks.shape)
print("size",marks.shape)
print("dtype",marks.dtype)
print("dimensions",marks.ndim)
# student wise total marks
total = np.sum(marks,axis= 1)
print(total)
# student wise average
average = np.mean(marks,axis = 1)
print(average)
# subjcet wise average
sub_avg = np.mean(marks,axis = 0)
print(sub_avg)
# highest and lowest marks
print("highest",np.max(marks))
print("Lowest",np.min(marks))
# top student
top = np.argmax(total)
print("Top student index",top)
print("Marks",marks[top])
# student above 80
print(marks[marks>80])
# Grace marks
new_mark =marks+5
print(new_mark)
# pass fail analysis
fail = marks<40
print(fail)
# count fail student
print(np.sum(fail))
# sort marks
print(np.sort(marks,axis =1))

[[86 49 95 55 58]
 [37 56 87 36 64]
 [72 36 98 94 55]
 [67 92 56 83 93]
 [76 94 49 96 96]
 [81 96 85 89 98]
 [37 85 41 55 73]
 [52 38 94 48 43]
 [87 36 94 78 42]
 [81 69 70 84 38]]
shape (10, 5)
size (10, 5)
dtype int64
dimensions 2
[343 280 355 391 411 449 291 275 337 342]
[68.6 56.  71.  78.2 82.2 89.8 58.2 55.  67.4 68.4]
[67.6 65.1 76.9 71.8 66. ]
highest 98
Lowest 36
Top student index 5
Marks [81 96 85 89 98]
[86 95 87 98 94 92 83 93 94 96 96 81 96 85 89 98 85 94 87 94 81 84]
[[ 91  54 100  60  63]
 [ 42  61  92  41  69]
 [ 77  41 103  99  60]
 [ 72  97  61  88  98]
 [ 81  99  54 101 101]
 [ 86 101  90  94 103]
 [ 42  90  46  60  78]
 [ 57  43  99  53  48]
 [ 92  41  99  83  47]
 [ 86  74  75  89  43]]
[[False False False False False]
 [ True False False  True False]
 [False  True False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [ True False False False False]
 [False  True False False False]
 [False  True False