<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day16_numpy_projcet/sales_projcet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Capstone Projcet : sales data analysis system

In [6]:
# import numpy
import numpy as np
# Genrate random sale data
np.random.seed(42)
sales = np.random.randint(1000,10000,size = (10,7))
print(sales)
# Explore the data
print("shape",sales.shape)
print("dimensions",sales.ndim)
print("size",sales.size)
print("data type",sales.dtype)
# Total sale of each store
total = np.sum(sales,axis =1)
print(total)
#Average sale
avg = np.mean(sales,axis =1)
print(avg)
# Day wise
print(np.mean(sales,axis = 0))
# Best performance store
best = np.argmax(total)
print(best)


[[8270 1860 6390 6191 6734 7265 1466]
 [5426 6578 9322 2685 1769 7949 3433]
 [6311 6051 7420 2184 5555 4385 7396]
 [9666 3558 8849 3047 3747 1189 3734]
 [4005 5658 2899 8734 2267 2528 4556]
 [4890 9838 6393 9792 9433 8513 3612]
 [8041 7235 6486 8099 1775 9226 4152]
 [2585 4943 8555 4073 2021 4843 8989]
 [7873 6675 1161 5297 1995 8629 2016]
 [8869 7439 8892 7863 8916 9529 1878]]
shape (10, 7)
dimensions 2
size 70
data type int64
[38176 37162 39302 33790 30647 52471 45014 36009 33646 53386]
[5453.71428571 5308.85714286 5614.57142857 4827.14285714 4378.14285714
 7495.85714286 6430.57142857 5144.14285714 4806.57142857 7626.57142857]
[6593.6 5983.5 6636.7 5796.5 4421.2 6405.6 4123.2]
9
