<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day15_numpy_Linear/class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 15 Numpy Linear Algebra  

Linear Algebra is the mathematical foundation of Machine Learning. Algorithms like Linear Regression, PCA, Neural Networks, and Transformers rely heavily on matrix operations.

1. import numpy

In [ ]:
import numpy as np

2. create matrix

In [ ]:
import numpy as np
a = np.array([
    [1,2],
    [3,4]
])
b = np.array([
    [5,6],
    [7,8]
])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


3. Matrux Addition

In [ ]:
print(a+b)

Output

[[ 6  8]
 [10 12]

4. Matrix Subtraction  

In [ ]:
print(a-b)

5. Matrix Multiplication

using np.dot():

In [ ]:
print(np.dot(a,b))

Using @ operator

In [ ]:
print(a@b)

6. Matrix transpose

In [ ]:
print(a.T)

or

In [ ]:
print(np.transpose(a))

7. Determinat

In [ ]:
print(np.linalg.det(a))

8. Matrix inverse

In [ ]:
print(np.linalg.inv(a))

9. Matrix rank

In [ ]:
print(np.linalg.matrix_rank(a))

10. Trace of a matrix

In [ ]:
print(np.trace(a))

11. Eigenvalues & Eigenvectors

In [ ]:
values, vectors = np.linalg.eig(A)

print("Eigenvalues:")
print(values)

print("Eigenvectors:")
print(vectors)

12. Slove a system of Equations  

slove :
° x+y = 5
° 2x + 3y = 13

In [ ]:
import numpy as np
a = np.array([
    [1,1],
    [2,3]
])
b = np.array([5,13])
print(np.linalg.solve(a,b))

[2. 3.]


13. Matrix Norm

In [ ]:
print(np.linalg.norm(A))

14. Identiy Matrix

In [ ]:
I = np.eye(3)

print(I)