<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day15_numpy_Linear/pratice_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Pratice Question

1.Create two 2×2 matrices.

2. Add them
3. Subtract them.
4. Multiply them using np.dot().
5. Find the transpose.
6. Find the determinant.7.7. Multiply them using @.
8. Find the inverse.
9. Find the rank.
10.Find the trace.

In [6]:
import numpy as np
a = ([
    [1,2],
    [3,4]
])
b = np.array([
    [6,7],
    [8,9]
])
print(a+b) # sum
print(a-b) # subtraction
print(np.dot(a,b)) # multiplication
print(a@b) # multiplication
print(np.transpose(a)) # transpose
print(np.linalg.det(a)) # detreamint
print(np.linalg.inv(b))# inverse
print(np.linalg.matrix_rank)
print(np.trace(a)) # trace

[[ 7  9]
 [11 13]]
[[-5 -5]
 [-5 -5]]
[[22 25]
 [50 57]]
[[22 25]
 [50 57]]
[[1 3]
 [2 4]]
-2.0000000000000004
[[-4.5  3.5]
 [ 4.  -3. ]]
<function matrix_rank at 0x7b87f316f2e0>
5
