<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day12_numpy_shape/class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 12 Numpy Reshape And Flatting

1. reshape()

Changes the shape of an array without changing its data.

In [ ]:
import numpy as np
arr = np.arange(1,11)
new_arr = arr.reshape(2,5)
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2. Reshape into 2d array

In [ ]:
import numpy as np
arr = np.arange(1,13)
new_arr = arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. Reshape into 3d array

In [ ]:
import numpy as np
arr = np.arange(1,25)
new_arr = arr.reshape(2,3,4)
print(new_arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


Using -1 in reshape

In [ ]:
import numpy as np
arr = np.arange(1,13)
print(arr.reshape(3,-1))
print(arr.reshape(-1,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


5. flatten()

Convert a multidimensional array into a new 1D array

In [ ]:
import numpy as np
arr = np.array([
    [1,2],
    [3,4]
])
flat = arr.flatten()
print(flat)

[1 2 3 4]


6. ravel()

Also converts an array into 1D, but usually returns a view of the original array.

In [ ]:
import numpy as np
arr = np.array([
    [1,2],
    [3,4]
])
ravel = arr.ravel()
print(ravel)

[1 2 3 4]


7. Difference between ravle() and flatten()

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
flat = arr.flatten()
ravel= arr.ravel()
flat[0] = 100
ravel[1] = 200
print(flat)
print(ravel)
print(arr)

[100   2   3   4   5   6]
[  1 200   3   4   5   6]
[[  1 200   3]
 [  4   5   6]]


key idea

° flatten() → returns a copy.
° ravel() → usually returns a view, so changes may affect the original array.

8. transpose()

Swap rows and columns

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


9. swapaxes()

In [12]:
import numpy as np
arr = np.arange(24).reshape(2,3,4)
new_arr = np.swapaxes(arr,0,1)
print(new_arr)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


10. resize()

In [13]:
import numpy as np
arr = np.array([[1,2],[3,4]])
arr.resize(2,2)
print(arr)

[[1 2]
 [3 4]]
