<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day12_numpy_shape/pratice_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratice Question

1. create an array to 1 to 12
2. Reshape it into 3×4.
3. Reshape it into 2×6.
4. Reshape it into 2×2×3
5. Use-1 with reshape

In [5]:
import numpy as np
arr = np.arange(1,13)
new_arr1 = arr.reshape(3,4)
new_arr2 = arr.reshape(2,6)
new_arr3 = arr.reshape(2,2,3)
print(new_arr1)
print(new_arr2)
print(new_arr3)
print(arr.reshape(3,-1))
print(arr.reshape(-1,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


5. use-1 w