<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day10_Numpy_Opeartion/class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 10 Numpy Array Operation

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

Addition

In [1]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 7  9 11 13 15]
[ 7  9 11 13 15]


3. Subtraction

In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]


4. Multiplication

In [4]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[ 6 14 24 36 50]
[ 6 14 24 36 50]


Division

In [7]:
import numpy as np
arr1 = np.array([6,7,8,9,10])
arr2 = np.array([1,2,3,4,5])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[6.         3.5        2.66666667 2.25       2.        ]
[6.         3.5        2.66666667 2.25       2.        ]


Floor division

In [ ]:
print(arr1 // arr2)

Modules

In [ ]:
print(arr1 % arr2)

Power

In [ ]:
print(arr2 ** 2)

Or

In [ ]:
print(np.power(arr2, 2))

Scaler Operation

In [ ]:
print(arr1 + 10)
print(arr1 * 5)
print(arr1 / 2)

Square root

In [ ]:
print(np.sqrt(arr1))

Exponential

In [ ]:
print(np.exp(arr2))

Logrthim

In [ ]:
print(np.log(arr1))

Absoulte value

In [ ]:
arr = np.array([-10, -20, 30, -40])

print(np.abs(arr))

Comparison Operator

In [ ]:
print(arr1 > 20)
print(arr1 == 30)
print(arr1 != 40)

Aggregation Function  

In [ ]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.max(arr1))
print(np.min(arr1))
print(np.std(arr1))