<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day10_Numpy_Opeartion/pratice_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratice Question

1. Create two arrays of five elements each.
2. Add the arrays.
3. Subtract the arrays.
4. Multiply the arrays.
5. Divide the arrays.
6. Find the square of every element.
7. Find the square root of every element.
8. Add 100 to every element.
9. Find the absolute values of a negative array.
10. Find the sum, mean, maximum, minimum, and standard deviation.

In [8]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,2,3,4,5])
print(np.add(arr1,arr2)) #Addition
print(np.subtract(arr1,arr2)) # Subtraction
print(np.multiply(arr1,arr2)) # multiplaction
print(np.divide(arr1,arr2)) # divide
print(np.power(arr1,2)) # square
print(np.sqrt(arr1)) # square Root
print(arr1+100)#Add 100 to array1
print(arr2+100)# Add 100 to second array


[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 100  400  900 1600 2500]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[110 120 130 140 150]
[101 102 103 104 105]


In [9]:
import numpy as np
arr = np.array([-1,-2,-3,-4,-5])
print(np.abs(arr)) #Absoulte value

[1 2 3 4 5]


In [10]:
import numpy as np
arr1 = np.array([10,20,30,40,50,60])
print(np.sum(arr1)) # sum
print(np.mean(arr1)) # mean
print(np.max(arr1)) # max
print(np.min(arr1)) # min
print(np.std(arr1)) # std

210
35.0
60
10
17.07825127659933
