<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day14_numpy_random/class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 14 Numpy Random Module

1. Import numpy

import numpy as np

2. np.random.rand

In [1]:
import numpy as np
a = np.random.rand()
print(a)

0.20814110896021254


3. np.random.randiant()

Genraye random integers

In [3]:
import numpy as np
print(np.random.randint(1,10))

9


Generate a (3,4)matrix

In [5]:
import numpy as np
print(np.random.randint(1,100,size =(3,4)))

[[93 40 13 69]
 [12 19 84 63]
 [36 70 11 54]]


4. np.random.randn()

Generates random numbers from the standard normal distribution (mean = 0, standard deviation = 1).

In [6]:
import numpy as np
print(np.random.randn(5))

[-1.67105286  1.70138553  1.04891528 -2.24382997  1.48414476]


2x3 matrix

In [7]:
import numpy as np
print(np.random.randn(2,3))

[[ 1.61849254 -0.88138079  0.05546808]
 [-0.10764204  0.02806368 -1.6340062 ]]


5. np.random.choice()

In [9]:
import numpy as np
colors =  ["RED","BLUE","GREEN","VOILET"]
print(np.random.choice(colors,size = 2))

['BLUE' 'VOILET']


6. np.random.seed()

In [11]:
import numpy as np
np.random.seed(42)
print(np.random.randint(1,100,5))

[52 93 15 72 61]


Running this code again with the same seed gives the same output.

7. np.random.shuffle

Shuffle an array in place

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)

print(arr)

[4 1 2 3 5]


8. np.random.permutaion

Returns a shuffled copy without changing the original array.

In [13]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

new_arr = np.random.permutation(arr)

print(new_arr)
print(arr)

[4 2 1 5 3]
[1 2 3 4 5]


9. Random decimal number

In [ ]:
print(np.random.random((3, 3)))

10. Random Floating-Point Numbers in a Range

In [ ]:
arr = np.random.uniform(10, 20, size=5)

print(arr)