<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day14_numpy_random/pratice_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratice Question

1. Generate a random float.

In [1]:
import numpy as np
print(np.random.rand())

0.5963885315709494


2. Genreate a 3x3 matrix

In [2]:
import numpy as np
print(np.random.rand(3,3))

[[0.87770151 0.23517058 0.46808007]
 [0.83983522 0.31884945 0.39203667]
 [0.92463749 0.13520224 0.9151684 ]]


3. Genreate fove integers between 1,100

In [4]:
import numpy as np
print(np.random.randint(1,100,size =(5)))

[31  3 95 25 36]


4. create a 4x4 random integer

In [5]:
import numpy as np
print(np.random.randint(1,50,size =(4,4)))

[[25  1  2 43]
 [44 36 24 35]
 [18 33  8 11]
 [41 17 48 30]]


5. Genreate five values using randan

In [8]:
import numpy as np
print(np.random.randn(5))

[-1.28795941 -1.40150557 -1.1636024   0.76313678  0.21898919]


6. select three random furit from the list

In [9]:
import numpy as np
fruit =["apple","banana","cherry","orange","guava"]
print(np.random.choice(fruit,size=3))

['banana' 'orange' 'banana']


7. set a random seed and  verfiy reproductbilty

In [14]:
import numpy as np
np.random.seed(42)
print(np.random.randint(1,100,5))

[52 93 15 72 61]


8. shuffle an array

In [15]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.random.shuffle(arr))

None
