<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day9_numpy_slicing/class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 9 Numpy index and slicing

1. Indexing in 1D array

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])

1
4


2. Slicing in 1D array

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:])
print(arr[:5])
print(arr[3:5])
print(arr[::2])
print(arr[::-1]) # reverse


[2 3 4 5 6 7]
[1 2 3 4 5]
[4 5]
[1 3 5 7]
[7 6 5 4 3 2 1]


Indexing in 2D array

In [4]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr[0,1])
print(arr[1,0])
print(arr[2,1])

2
4
8


Slicing in 2D array

In [5]:
import numpy as np
iarr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,:]) #first row
print(arr[:,1]) # second coloum
print(arr[:2,:]) # first two rows
print(arr[1:,1:]) # center elements

[1 2 3]
[2 5 8]
[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]


5.Indexing in 3D array

In [7]:
import numpy as np
arr =np.array([
    [[10,20,30],[40,50,60]],
    [[70,80,90],[110,120,130]]
])
print(arr[0,0,1])
print(arr[1,1,1])

20
120


6. Fancy indexing

In [9]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[[0,3,4]])

[10 40 50]


7.Bollean Indxing

In [10]:
arr = np.array([10,20,30,40,50,60])
print(arr[arr>25])

[30 40 50 60]


Negative indexing

In [11]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[-1])
print(arr[-4:-1])

60
[30 40 50]


9. Step slicing

In [12]:
import numpy as np
arr = np.arange(1,11)
print(arr[2:9:2])

[3 5 7 9]


Modifying  Element

In [13]:
import numpy as np
arr = np.array([10,20,30,40,50])
arr[0] = 100
print(arr)


[100  20  30  40  50]
