<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day9_numpy_slicing/pratice_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratice Question

1. create a 1D array of 10 elements

In [ ]:
import numpy as np
arr =np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


print the first middle and last element

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0])
print(arr[9])
print(arr[4])

1
10
5


3. Reverse the array

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[::-1])


[9 8 7 6 5 4 3 2 1]


4. print fancy indexing to select elements

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[[2,4,5]])

[3 5 6]


use the boolean indexing to print value greater  than 25

In [5]:
import numpy as np
arr = np.array([10,20,30,40,50,60,79])
print(arr[arr<25])

[10 20]
