<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day8_Numpy_basic/class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Day 9  Introduction to Numpy

NumPy (Numerical Python) is a Python library used for:

Fast numerical calculations
Working with multidimensional arrays
Mathematical operations
Statistics
Linear algebra
Random number generation

imoprt numpy

In [ ]:
import numpy as np


Check the the insatlled version

In [2]:
import numpy as np
print(np.__version__)

2.0.2


3. creating arrays

1D Array

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2D Array

In [4]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


3D Array

In [8]:
import numpy as np
arr = np.array([
    [[1,2,3],[3,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr)


[[[ 1  2  3]
  [ 3  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


4. Array Proprities

In [10]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


5. Sepcial array

Zeros

In [12]:
import numpy as np
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ones

In [13]:
import numpy as np
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Identy Matrix

In [15]:
import numpy as np
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Empty arrays

In [16]:
import numpy as np
print(np.empty((2,2)))

[[1. 1.]
 [1. 1.]]


6. creating array with

arange()

In [17]:
import numpy as np
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


with step

In [18]:
import numpy as np
print(np.arange(1,21,2))

[ 1  3  5  7  9 11 13 15 17 19]


7. creating array with

linspace()

In [19]:
import numpy as np
print(np.linspace(0,10,6,))

[ 0.  2.  4.  6.  8. 10.]
