<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day8_Numpy_basic/pratice_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratice Question

1. import numpy

In [ ]:
import numpy as np

2. print numpy version

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


3. create a 1D array of 10 integer

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


4. create a 2d arryay

In [ ]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
2


5. create  a 3d array

In [ ]:
import numpy as np
arr = np.array([
    [[1,2,],[3,4]],
    [[6,7,],[8,9]]
])
print(arr)
print(arr.ndim)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]
3


6. Print
   °ndim
   °shape
   °size
   °dtype

In [ ]:
import numpy as np
arr = np.array([
    [1,2],
    [3,4]
])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 2)
4
int64


Create ° A 4X4 zero matrix ° A 3x5 ones matrix ° A 5x5 identy matrix

In [7]:
import numpy as np
print(np.zeros((4,4)))
print(np.ones((3,5)))
print(np.eye(5))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
