<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day11_numpy_brodcasting/class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What is Broadcasting

Broadcasting automatically expands the smaller array to match the larger array's shape during operations.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr+10)

[11 12 13 14 15 16 17]


2. Broadcasting with scaler

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr+10)
print(arr*2)

[11 12 13]
[2 4 6]


3. Broadcasting between arrays

In [ ]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
print(arr1+arr2)

[50 70 90]


4. Broadcasting in 2D array

In [ ]:
import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr+10)

[[11 12 13]
 [14 15 16]]


5. Broadcasting Row-wise

In [ ]:
import numpy as np
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
row = np.array([10,20,30])
print(matrix + row)

[[11 22 33]
 [14 25 36]]


6. Broadcasting Coloumn- wise  

In [ ]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
        [4, 5, 6]
        ])
column = np.array([[10],
                   [20]])

print(matrix + column)

[[11 12 13]
 [24 25 26]]


7. Broadcasting Rules

Two dimensions are compatible if:
They are equal, or
One of them is 1

Example(works)

(2,3)
(1,3)

Example(works)

(2,3)
(2,1)

Example(error)

(2,3)
(4,3)

8. Broadcasting with multiplication

In [ ]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])
print(arr * 5)

TypeError: 'list' object is not callable