<a href="https://colab.research.google.com/github/vaibhav2005vk-cloud/Python-numpy-pandas-matplotlib-EDA/blob/main/Day11_numpy_brodcasting/pratice_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pratice Question

1. Add 5 to every element of an array

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr+5)

[15 25 35 45]


2. Multiply every element by 2

In [ ]:
import numpy as np
arr = np.array([10,20,30])
print(arr*2)

[20 40 60]


3. Divide every element by 2

In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr / 2)

[[ 5. 10. 15.]
 [20. 25. 30.]]


4. Add  two 1D arrays

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = ([5,6,7,8])
print(arr1+arr2)

[1, 2, 3, 4, 5, 6, 7, 8]


5. Add a row vector to a 2D matrix

In [1]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
row = np.array([10,20,30])
print(matrix +row)

[[11 22 33]
 [14 25 36]]


7.Multiple a matrix by 3

In [2]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix*3)

[[ 3  6  9]
 [12 15 18]]


8. create a 2d matrix and add them

In [4]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1+arr2)

[[ 2  4  6]
 [ 8 10 12]]
